spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    host: 10.5.222.197
    port: 5672
    username: admin
    password: Qw12
    virtual-host: dev
    listener:
      simple:
        prefetch: 1
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
    jooq:
      sql-dialect: mariadb
  logging:
    level:
      root: info
  datasource:
    url: jdbc:mariadb://localhost:3306/configuration
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none